### ISSUE TITLE
Cannot Specify Script Variables

### ISSUE THREAD

**Issue by monkeylittle** [monkeylittleinc/jenkins_plugins#4]
I need to be able to parameterise the script with user defined variables.  For example, I will want to be able to specify the SCM url etc.

**Comment by samdunne** [comment]
You can like so:

``` ruby
jenkins_plugins_workflow 'workflow-job' do
  script 'hello-world.groovy.erb'
  variables ({
    test_one: "Hello",
    test: {
      two: "World!"
    }
  })
end

```

**NOTE:** The `()` brackets around the hash are important. Otherwise it will be interpreted incorrectly.

I'll add this to the documentation and close this issue.
